### ISSUE TITLE
Fetch Feeds error : SSL operation failed - OpenSSL - error:1408F10B:SSL routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by qjadoun** [NUKIB/misp#127]
Hi,
I am struggling to make it work and fetch feeds

OS: redhat 8.80 
Env:
- behind proxy with SSL inspection
- curl to URL is ok by executing it inside the container.
Result: 
- warning: error:1408F10B:SSL routines:ssl3_get_record:wrong version number in [/var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Network/CakeSocket.php

Sep 27 14:27:34 0323e4204a28 MISP: warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
Sep 27 14:27:34 0323e4204a28 MISP: warning: error:1408F10B:SSL routines:ssl3_get_record:wrong version number in [/var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Network/CakeSocket.php, line 504]
Sep 27 14:27:34 0323e4204a28 MISP: error: Could not get freetext feed 17
Sep 27 14:27:34 0323e4204a28 MISP: error: [Exception] Fetching the 'https://cinsscore.com/list/ci-badguys.txt' failed with exception: Unable to perform enableCrypto operation on CakeSocket
Sep 27 14:27:34 0323e4204a28 MISP: error: Stack Trace:
Sep 27 14:27:34 0323e4204a28 MISP: error: #0 /var/www/MISP/app/Model/Feed.php(343): Feed->feedGetUriRemote()
Sep 27 14:27:34 0323e4204a28 MISP: error: #1 /var/www/MISP/app/Model/Feed.php(382): Feed->getFreetextFeedRemote()
Sep 27 14:27:34 0323e4204a28 MISP: error: #2 /var/www/MISP/app/Model/Feed.php(1190): Feed->getFreetextFeed()
Sep 27 14:27:34 0323e4204a28 MISP: error: #3 /var/www/MISP/app/Console/Command/ServerShell.php(404): Feed->downloadFromFeedInitiator()
Sep 27 14:27:34 0323e4204a28 MISP: error: #4 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->fetchFeed()
Sep 27 14:27:34 0323e4204a28 MISP: error: #5 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
Sep 27 14:27:34 0323e4204a28 MISP: error: #6 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
Sep 27 14:27:34 0323e4204a28 MISP: error: #7 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
Sep 27 14:27:34 0323e4204a28 MISP: error: #8 {main}[SocketException] Unable to perform enableCrypto operation on CakeSocket

**Comment by benLewisDev** [comment]
I'm also seeing this exact same error.

**Comment by Benni0** [comment]
Did you import your custom root CA?
https://github.com/NUKIB/misp/blob/main/docs/CUSTOMIZATION.md#add-custom-certificates

**Comment by ondj** [comment]
@qjadoun Hello, thanks for report. Can you please check if your proxy supports TLSv1.2 or TLSv1.3? This container enforce usage of TLSv1.2 or newer.
