### ISSUE TITLE
Could noet users in release 2.4.196

### ISSUE THREAD

**Issue by clopmz** [NUKIB/misp#177]
HI all,

When I try to add an user in release 2.4.196, the following error appears: "An Internal Error Has Occurred.". In error.log file:

2024-09-01 10:35:17 Error: [Error] Method EncryptedValue::__toString() must return a string value
Request URL: /admin/users/add
Stack Trace:
#0 /var/www/MISP/app/View/Users/admin_add.ctp(38): h()
#1 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/View/View.php(971): include('/var/www/MISP/a...')
#2 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/View/View.php(933): View->_evaluate()
#3 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/View/View.php(473): View->_render()
#4 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php(968): View->render()
#5 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#6 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#8 {main}

Do I need to enable/disable some option? Or is it a bug?

**Comment by jowilsonfo** [comment]
I'm with the same problem in release 2.4.198.
