### ISSUE TITLE
Crash Loop regarding KeyError: 'loading'

### ISSUE THREAD

**Issue by phekaufmann** [NUKIB/misp#182]
Traceback (most recent call last):
2024-09-05T20:50:47.675609390Z   File "/usr/local/bin/misp_redis_ready.py", line 97, in <module>
2024-09-05T20:50:47.675691114Z     main()
2024-09-05T20:50:47.675696213Z   File "/usr/local/bin/misp_redis_ready.py", line 93, in main
2024-09-05T20:50:47.675764672Z     wait_for_load(redis)
2024-09-05T20:50:47.675769631Z   File "/usr/local/bin/misp_redis_ready.py", line 59, in wait_for_load
2024-09-05T20:50:47.675830626Z     if persistence["loading"]:
2024-09-05T20:50:47.675837429Z        ~~~~~~~~~~~^^^^^^^^^^^
2024-09-05T20:50:47.675849593Z KeyError: 'loading'

It looks like this has to do with Redis, and I was unsure if this is something I should be modifying persistence values in Redis or is a genuine problem with the code. Appreciate any help!

**Comment by ondj** [comment]
@phekaufmann Fixed, thanks for report.
