### ISSUE TITLE
ValueError: badly formed hexadecimal UUID string and not valid salt

### ISSUE THREAD

**Issue by lokalhorstkme** [NUKIB/misp#65]
Could not get misp container to running state. Could you please give me a hint where my error in docker-compose.yml is?

MISP_UUID: 2832648a-7971-11ed-a1eb-0242ac120002 
SECURITY_SALT: 1SBEymWHDD4jPY88KA3ATpYUxHA3d6enkUq/4wu0RTw= 

Logs:
misp            | Warning: 'SECURITY_SALT' environment variable should be at least 32 chars long
misp            | Traceback (most recent call last):
misp            |   File "/usr/local/bin/misp_create_configs.py", line 398, in <module>
misp            |     main()
misp            |   File "/usr/local/bin/misp_create_configs.py", line 352, in main
misp            |     uuid.UUID(variables["MISP_UUID"])
misp            |   File "/usr/lib64/python3.9/uuid.py", line 177, in __init__
misp            |     raise ValueError('badly formed hexadecimal UUID string')
misp            | ValueError: badly formed hexadecimal UUID string
misp exited with code 1

**Comment by ondj** [comment]
Hello, thanks for report! Can you please try it with latest version? At least MISP should give you much better error message, because currently I don't understand why this doesn't work.
